#! /usr/bin/python
# -*- coding: utf-8 -*-

from rhevmtests.compute.virt.config import *  # flake8: noqa

RHEL_IMG_VM_BASE = 'rhel_guest_img_%s_vm'
RHEL_IMG_TEMPLATE_BASE = 'rhel_guest_img_%s_template'
RHEL_IMG_POOL_BASE = 'rhel_guest_img_%s_pool'
RHEL_IMG_POOL_WITHOUT_PASSWORD_BASE = (
    'rhel_guest_img_%s_pool_without_password'
)
IMAGE_VERSION_6_9 = '6_9'
IMAGE_VERSION_7_5 = '7_5'
# image rhel 6.9 info
RHEL_IMG_69 = 'latest-rhel-guest-image-6.9'
RHEL_IMG_69_VM = RHEL_IMG_VM_BASE % IMAGE_VERSION_6_9
RHEL_IMG_69_TEMPLATE = RHEL_IMG_TEMPLATE_BASE % IMAGE_VERSION_6_9
RHEL_IMG_69_POOL = RHEL_IMG_POOL_BASE % IMAGE_VERSION_6_9
RHEL_IMG_69_POOL_WITHOUT_PASSWORD = (
    RHEL_IMG_POOL_WITHOUT_PASSWORD_BASE % IMAGE_VERSION_6_9
)
# image rhel 7.5 info
RHEL_IMG_75 = 'latest-rhel-guest-image-75'
RHEL_IMG_75_VM = RHEL_IMG_VM_BASE % IMAGE_VERSION_7_5
RHEL_IMG_75_TEMPLATE = RHEL_IMG_TEMPLATE_BASE % IMAGE_VERSION_7_5
RHEL_IMG_75_POOL = RHEL_IMG_POOL_BASE % IMAGE_VERSION_7_5
RHEL_IMG_75_POOL_WITHOUT_PASSWORD = (
    RHEL_IMG_POOL_WITHOUT_PASSWORD_BASE % IMAGE_VERSION_7_5
)
# templates, vms, pools names
RHEL_IMG_LIST = [RHEL_IMG_75]
TESTED_VMS_NAMES = [RHEL_IMG_75_VM]
TEMPLATES_NAMES = [RHEL_IMG_75_TEMPLATE]
IMG_TO_TEMPLATE_NAME = {
    # RHEL_IMG_69: RHEL_IMG_69_TEMPLATE,
    RHEL_IMG_75: RHEL_IMG_75_TEMPLATE
}
TAMPLATE_TO_VM_NAME = {
    # RHEL_IMG_69_VM: RHEL_IMG_69_TEMPLATE,
    RHEL_IMG_75_VM: RHEL_IMG_75_TEMPLATE
}

HOST_NAME = 'guest_image_test'
