"""
Config module for storage domain lifecycle tests
"""
from rhevmtests.storage.config import *  # flake8: noqa

TESTNAME = "domain_lifecycle"

DC_VERSIONS = COMP_VERSION_4_0[:]
DC_UPGRADE_VERSIONS = [COMPATIBILITY_VERSION]
LIFECYCLE_VM = "%s_vm" % TESTNAME
EXTRA_SD_INDEX = 3
DATA_CENTER_INIT_TIMEOUT = 300

if STORAGE_TYPE == STORAGE_TYPE_POSIX:
    # Force POSIX to be mounted as NFS
    STORAGE_TYPE = STORAGE_TYPE_NFS
CLI_CMD_DF = 'df -H'

ISCSI = STORAGE_TYPE_ISCSI
GLUSTER = STORAGE_TYPE_GLUSTER
NFS = STORAGE_TYPE_NFS
CEPH = STORAGE_TYPE_CEPH
FCP = STORAGE_TYPE_FCP
