"""
Config module for storage qcow2_v3 tests
"""
from rhevmtests.storage.config import *  # flake8: noqa

if STORAGE_TYPE == STORAGE_TYPE_POSIX:
    # Force POSIX to be mounted as NFS
    STORAGE_TYPE = STORAGE_TYPE_NFS

ISCSI = STORAGE_TYPE_ISCSI
GLUSTER = STORAGE_TYPE_GLUSTER
NFS = STORAGE_TYPE_NFS
CEPH = STORAGE_TYPE_CEPH
FCP = STORAGE_TYPE_FCP
POLL_PERIOD = 10
CREATE_TEMPLATE_TIMEOUT = 1800