from rhevmtests.virt.config import *  # flake8: noqa

RHEL_IMG_VM_BASE = 'rhel_guest_img_%s_vm'
RHEL_IMG_TEMPLATE_BASE = 'rhel_guest_img_%s_template'
RHEL_IMG_POOL_BASE = 'rhel_guest_img_%s_pool'
RHEL_IMG_POOL_WITHOUT_PASSWORD_BASE = (
    'rhel_guest_img_%s_pool_without_password'
)
IMAGE_VERSION_6_9 = '6_9'
IMAGE_VERSION_7_4 = '7_4'
# image rhel 6.9 info
RHEL_IMG_69 = 'latest-rhel-guest-image-6.9'
RHEL_IMG_69_VM = RHEL_IMG_VM_BASE % IMAGE_VERSION_6_9
RHEL_IMG_69_TEMPLATE = RHEL_IMG_TEMPLATE_BASE % IMAGE_VERSION_6_9
RHEL_IMG_69_POOL = RHEL_IMG_POOL_BASE % IMAGE_VERSION_6_9
RHEL_IMG_69_POOL_WITHOUT_PASSWORD = (
    RHEL_IMG_POOL_WITHOUT_PASSWORD_BASE % IMAGE_VERSION_6_9
)
# image rhel 7.4 info
RHEL_IMG_74 = 'latest-rhel-guest-image-7.4'
RHEL_IMG_74_VM = RHEL_IMG_VM_BASE % IMAGE_VERSION_7_4
RHEL_IMG_74_TEMPLATE = RHEL_IMG_TEMPLATE_BASE % IMAGE_VERSION_7_4
RHEL_IMG_74_POOL = RHEL_IMG_POOL_BASE % IMAGE_VERSION_7_4
RHEL_IMG_74_POOL_WITHOUT_PASSWORD = (
    RHEL_IMG_POOL_WITHOUT_PASSWORD_BASE % IMAGE_VERSION_7_4
)
# templates, vms, pools names
RHEL_IMG_LIST = [RHEL_IMG_69, RHEL_IMG_74]
TESTED_VMS_NAMES = [RHEL_IMG_69_VM, RHEL_IMG_74_VM]
TEMPLATES_NAMES = [RHEL_IMG_69_TEMPLATE, RHEL_IMG_74_TEMPLATE]
IMG_TO_TEMPLATE_NAME = {
    RHEL_IMG_69: RHEL_IMG_69_TEMPLATE,
    RHEL_IMG_74: RHEL_IMG_74_TEMPLATE
}
TAMPLATE_TO_VM_NAME = {
    RHEL_IMG_69_VM: RHEL_IMG_69_TEMPLATE,
    RHEL_IMG_74_VM: RHEL_IMG_74_TEMPLATE
}

HOST_NAME = 'guest_image_test'
