def verify_uuid(uuid, uuid_via_cmd, uuid_via_resource):
    """
    Verify proper UUID was assigned to a VM.

    Args:
        uuid (str): uuid assigned to VM by user, if such exists (can be none if
                    uuid supposed to be generated by Engine.)
        uuid_via_cmd (str): UUID obtained by executing "dmidecode -s system
                            uuid" command on VM.
        uuid_via_resource (str): UUID obtained from VM object.

    Raises:
        Assertion error: In case some of uuid is not as expected.
    """
    if uuid:
        assert uuid == uuid_via_cmd == uuid_via_resource, (
            "UUID mismatch: obtained from dmidecode cmd - {uuid_cmd}; "
            "obtained from resource object {uuid_resource}; "
            "uuid originaly set: {original_uuid}".format(
                uuid_cmd=uuid_via_cmd,
                uuid_resource=uuid_via_resource,
                original_uuid=uuid
            )
        )
    else:
        assert uuid_via_cmd == uuid_via_resource, (
            "UUID mismatch: obtained from dmidecode cmd - {uuid_cmd}; "
            "obtained from resource object {uuid_resource}; ".format(
                uuid_cmd=uuid_via_cmd,
                uuid_resource=uuid_via_resource
            )
        )
