#! /usr/bin/python
# -*- coding: utf-8 -*-

"""
Migration config file
"""
from rhevmtests.compute.virt.config import *  # flake8: noqa

CANCEL_VM_MIGRATE = False
MIGRATION_VM = VM_NAME[0]
MIGRATION_VM_LOAD = "virt_migration_vm"
CONNECTIVITY_CHECK = False if PPC_ARCH else True
MIGRATION_IMAGE_VM = "vm_with_loadTool"
OS_RHEL_7 = ENUMS['rhel7x64']
HOST_INDEX_MAX_MEMORY = -1
DATA_CENTER_NAME = DC_NAME[0]

# migration policy name
MIGRATION_POLICY_MINIMAL_DOWNTIME = 'minimal_downtime'
MIGRATION_POLICY_LEGACY = 'legacy'
MIGRATION_POLICY_SUSPEND_WORK_IF_NEEDED = 'suspend_workload_if_needed'
MIGRATION_POLICY_POST_COPY = 'post_copy_migration'
MIGRATION_POLICY_INHERIT = 'inherit'  # inherit from policy cluster
MIGRATION_POLICY_NAMES = [
    MIGRATION_POLICY_MINIMAL_DOWNTIME, MIGRATION_POLICY_LEGACY,
    MIGRATION_POLICY_SUSPEND_WORK_IF_NEEDED, MIGRATION_POLICY_POST_COPY
]
# migration policy map name to id
MIGRATION_POLICIES = {
    MIGRATION_POLICY_MINIMAL_DOWNTIME: '80554327-0569-496b-bdeb-fcbbf52b827b',
    MIGRATION_POLICY_LEGACY: '00000000-0000-0000-0000-000000000000',
    MIGRATION_POLICY_SUSPEND_WORK_IF_NEEDED:
        '80554327-0569-496b-bdeb-fcbbf52b827c',
    MIGRATION_POLICY_POST_COPY: 'a7aeedb2-8d66-4e51-bb22-32595027ce71',
    MIGRATION_POLICY_INHERIT: 'inherit'
}
BW_AUTO = 'auto'
BW_HYPERVISOR_DEFAULT = 'hypervisor_default'
BW_CUSTOM = 'custom'

CUSTOM_BW_32_MBPS = 32
HYPERVISOR_DEFAULT_BW = 52

MIGRATION_TIMEOUT = 300
